apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gkm-csi-node
spec:
  template:
    spec:
      nodeSelector:
        hardware-type: gpu
      tolerations:
        - key: gpu
          operator: Equal
          value: "true"
          effect: NoSchedule
