resources:
- ../default

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: gkm-agent
    path: agent-patch.yaml
