resources:
- ../default

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: gkm-agent
    path: agent-patch.yaml
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: gkm-csi-node
    path: csi-patch.yaml
