resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/tkm/operator
  newTag: latest
- name: quay.io/tkm/operator
  newName: quay.io/tkm/operator
  newTag: latest
