---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: gkm-test-ds-3
  namespace: gkm-test-ns-1
  labels:
    gkm.io/pvc-mutation: "true"
spec:
  selector:
    matchLabels:
      name: gkm-test-ds-3
  template:
    metadata:
      labels:
        name: gkm-test-ds-3
        gkm.io/pvc-mutation: "true"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: test
          image: quay.io/fedora/fedora-minimal
          imagePullPolicy: IfNotPresent
          command: [sleep, 365d]
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: kernel-volume
              mountPath: /cache
      volumes:
        - name: kernel-volume
          persistentVolumeClaim:
            claimName: gkm-test-obj
