---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gkm-io-v1alpha1-clustergkmcache
  failurePolicy: Fail
  name: mclustergkmcache.kb.io
  rules:
  - apiGroups:
    - gkm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustergkmcaches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gkm-io-v1alpha1-gkmcache
  failurePolicy: Fail
  name: mgkmcache.kb.io
  rules:
  - apiGroups:
    - gkm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gkmcaches
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gkm-io-v1alpha1-clustergkmcache
  failurePolicy: Fail
  name: vclustergkmcache.kb.io
  rules:
  - apiGroups:
    - gkm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustergkmcaches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gkm-io-v1alpha1-gkmcache
  failurePolicy: Fail
  name: vgkmcache.kb.io
  rules:
  - apiGroups:
    - gkm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gkmcaches
  sideEffects: None
