---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-tkm-io-v1alpha1-clustertkmcache
  failurePolicy: Fail
  name: mclustertkmcache.kb.io
  rules:
  - apiGroups:
    - tkm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustertkmcaches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-tkm-io-v1alpha1-tkmcache
  failurePolicy: Fail
  name: mtkmcache.kb.io
  rules:
  - apiGroups:
    - tkm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tkmcaches
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tkm-io-v1alpha1-clustertkmcache
  failurePolicy: Fail
  name: vclustertkmcache.kb.io
  rules:
  - apiGroups:
    - tkm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustertkmcaches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tkm-io-v1alpha1-tkmcache
  failurePolicy: Fail
  name: vtkmcache.kb.io
  rules:
  - apiGroups:
    - tkm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tkmcaches
  sideEffects: None
