// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: gkm-csi.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GkmCsiService_LoadKernelImage_FullMethodName   = "/gkmCsi.GkmCsiService/LoadKernelImage"
	GkmCsiService_UnloadKernelImage_FullMethodName = "/gkmCsi.GkmCsiService/UnloadKernelImage"
)

// GkmCsiServiceClient is the client API for GkmCsiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GkmCsiServiceClient interface {
	LoadKernelImage(ctx context.Context, in *LoadKernelImageRequest, opts ...grpc.CallOption) (*LoadKernelImageResponse, error)
	UnloadKernelImage(ctx context.Context, in *UnloadKernelImageRequest, opts ...grpc.CallOption) (*UnloadKernelImageResponse, error)
}

type gkmCsiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGkmCsiServiceClient(cc grpc.ClientConnInterface) GkmCsiServiceClient {
	return &gkmCsiServiceClient{cc}
}

func (c *gkmCsiServiceClient) LoadKernelImage(ctx context.Context, in *LoadKernelImageRequest, opts ...grpc.CallOption) (*LoadKernelImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadKernelImageResponse)
	err := c.cc.Invoke(ctx, GkmCsiService_LoadKernelImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gkmCsiServiceClient) UnloadKernelImage(ctx context.Context, in *UnloadKernelImageRequest, opts ...grpc.CallOption) (*UnloadKernelImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadKernelImageResponse)
	err := c.cc.Invoke(ctx, GkmCsiService_UnloadKernelImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GkmCsiServiceServer is the server API for GkmCsiService service.
// All implementations must embed UnimplementedGkmCsiServiceServer
// for forward compatibility.
type GkmCsiServiceServer interface {
	LoadKernelImage(context.Context, *LoadKernelImageRequest) (*LoadKernelImageResponse, error)
	UnloadKernelImage(context.Context, *UnloadKernelImageRequest) (*UnloadKernelImageResponse, error)
	mustEmbedUnimplementedGkmCsiServiceServer()
}

// UnimplementedGkmCsiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGkmCsiServiceServer struct{}

func (UnimplementedGkmCsiServiceServer) LoadKernelImage(context.Context, *LoadKernelImageRequest) (*LoadKernelImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadKernelImage not implemented")
}
func (UnimplementedGkmCsiServiceServer) UnloadKernelImage(context.Context, *UnloadKernelImageRequest) (*UnloadKernelImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadKernelImage not implemented")
}
func (UnimplementedGkmCsiServiceServer) mustEmbedUnimplementedGkmCsiServiceServer() {}
func (UnimplementedGkmCsiServiceServer) testEmbeddedByValue()                       {}

// UnsafeGkmCsiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GkmCsiServiceServer will
// result in compilation errors.
type UnsafeGkmCsiServiceServer interface {
	mustEmbedUnimplementedGkmCsiServiceServer()
}

func RegisterGkmCsiServiceServer(s grpc.ServiceRegistrar, srv GkmCsiServiceServer) {
	// If the following call pancis, it indicates UnimplementedGkmCsiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GkmCsiService_ServiceDesc, srv)
}

func _GkmCsiService_LoadKernelImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadKernelImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GkmCsiServiceServer).LoadKernelImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GkmCsiService_LoadKernelImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GkmCsiServiceServer).LoadKernelImage(ctx, req.(*LoadKernelImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GkmCsiService_UnloadKernelImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadKernelImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GkmCsiServiceServer).UnloadKernelImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GkmCsiService_UnloadKernelImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GkmCsiServiceServer).UnloadKernelImage(ctx, req.(*UnloadKernelImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GkmCsiService_ServiceDesc is the grpc.ServiceDesc for GkmCsiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GkmCsiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gkmCsi.GkmCsiService",
	HandlerType: (*GkmCsiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadKernelImage",
			Handler:    _GkmCsiService_LoadKernelImage_Handler,
		},
		{
			MethodName: "UnloadKernelImage",
			Handler:    _GkmCsiService_UnloadKernelImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gkm-csi.proto",
}
