// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: gkm-csi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageLocation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ImagePullPolicy *int32                 `protobuf:"varint,2,opt,name=image_pull_policy,json=imagePullPolicy,proto3,oneof" json:"image_pull_policy,omitempty"`
	Username        *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password        *string                `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImageLocation) Reset() {
	*x = ImageLocation{}
	mi := &file_gkm_csi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageLocation) ProtoMessage() {}

func (x *ImageLocation) ProtoReflect() protoreflect.Message {
	mi := &file_gkm_csi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageLocation.ProtoReflect.Descriptor instead.
func (*ImageLocation) Descriptor() ([]byte, []int) {
	return file_gkm_csi_proto_rawDescGZIP(), []int{0}
}

func (x *ImageLocation) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageLocation) GetImagePullPolicy() int32 {
	if x != nil && x.ImagePullPolicy != nil {
		return *x.ImagePullPolicy
	}
	return 0
}

func (x *ImageLocation) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *ImageLocation) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

// LoadKernelImageRequest represents a request to load a GPU Kernel Cache from
// an OCI Image.
type LoadKernelImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImageLocation         `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadKernelImageRequest) Reset() {
	*x = LoadKernelImageRequest{}
	mi := &file_gkm_csi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadKernelImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadKernelImageRequest) ProtoMessage() {}

func (x *LoadKernelImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gkm_csi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadKernelImageRequest.ProtoReflect.Descriptor instead.
func (*LoadKernelImageRequest) Descriptor() ([]byte, []int) {
	return file_gkm_csi_proto_rawDescGZIP(), []int{1}
}

func (x *LoadKernelImageRequest) GetImage() *ImageLocation {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *LoadKernelImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadKernelImageRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

// LoadKernelImageResponse represents a response from loading a GPU Kernel Cache from
// an OCI Image. The response contains success or failure
type LoadKernelImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadKernelImageResponse) Reset() {
	*x = LoadKernelImageResponse{}
	mi := &file_gkm_csi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadKernelImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadKernelImageResponse) ProtoMessage() {}

func (x *LoadKernelImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gkm_csi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadKernelImageResponse.ProtoReflect.Descriptor instead.
func (*LoadKernelImageResponse) Descriptor() ([]byte, []int) {
	return file_gkm_csi_proto_rawDescGZIP(), []int{2}
}

func (x *LoadKernelImageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UnloadKernelImageRequest represents a request to unload/delete a GPU Kernel Cache
// from the local filesystem.
type UnloadKernelImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadKernelImageRequest) Reset() {
	*x = UnloadKernelImageRequest{}
	mi := &file_gkm_csi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadKernelImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadKernelImageRequest) ProtoMessage() {}

func (x *UnloadKernelImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gkm_csi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadKernelImageRequest.ProtoReflect.Descriptor instead.
func (*UnloadKernelImageRequest) Descriptor() ([]byte, []int) {
	return file_gkm_csi_proto_rawDescGZIP(), []int{3}
}

func (x *UnloadKernelImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnloadKernelImageRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

// UnloadKernelImageResponse represents a response from unloading a GPU Kernel Cache
// from the local filesystem. The response contains success or failure
type UnloadKernelImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadKernelImageResponse) Reset() {
	*x = UnloadKernelImageResponse{}
	mi := &file_gkm_csi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadKernelImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadKernelImageResponse) ProtoMessage() {}

func (x *UnloadKernelImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gkm_csi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadKernelImageResponse.ProtoReflect.Descriptor instead.
func (*UnloadKernelImageResponse) Descriptor() ([]byte, []int) {
	return file_gkm_csi_proto_rawDescGZIP(), []int{4}
}

func (x *UnloadKernelImageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gkm_csi_proto protoreflect.FileDescriptor

const file_gkm_csi_proto_rawDesc = "" +
	"\n" +
	"\rgkm-csi.proto\x12\x06gkmCsi\"\xc4\x01\n" +
	"\rImageLocation\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12/\n" +
	"\x11image_pull_policy\x18\x02 \x01(\x05H\x00R\x0fimagePullPolicy\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x01R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tH\x02R\bpassword\x88\x01\x01B\x14\n" +
	"\x12_image_pull_policyB\v\n" +
	"\t_usernameB\v\n" +
	"\t_password\"\x8a\x01\n" +
	"\x16LoadKernelImageRequest\x12+\n" +
	"\x05image\x18\x01 \x01(\v2\x15.gkmCsi.ImageLocationR\x05image\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"3\n" +
	"\x17LoadKernelImageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"_\n" +
	"\x18UnloadKernelImageRequest\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"5\n" +
	"\x19UnloadKernelImageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc1\x01\n" +
	"\rGkmCsiService\x12T\n" +
	"\x0fLoadKernelImage\x12\x1e.gkmCsi.LoadKernelImageRequest\x1a\x1f.gkmCsi.LoadKernelImageResponse\"\x00\x12Z\n" +
	"\x11UnloadKernelImage\x12 .gkmCsi.UnloadKernelImageRequest\x1a!.gkmCsi.UnloadKernelImageResponse\"\x00B3Z1github.com/redhat-et/GKM/pkg/gkm-csi-plugin/protob\x06proto3"

var (
	file_gkm_csi_proto_rawDescOnce sync.Once
	file_gkm_csi_proto_rawDescData []byte
)

func file_gkm_csi_proto_rawDescGZIP() []byte {
	file_gkm_csi_proto_rawDescOnce.Do(func() {
		file_gkm_csi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gkm_csi_proto_rawDesc), len(file_gkm_csi_proto_rawDesc)))
	})
	return file_gkm_csi_proto_rawDescData
}

var file_gkm_csi_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gkm_csi_proto_goTypes = []any{
	(*ImageLocation)(nil),             // 0: gkmCsi.ImageLocation
	(*LoadKernelImageRequest)(nil),    // 1: gkmCsi.LoadKernelImageRequest
	(*LoadKernelImageResponse)(nil),   // 2: gkmCsi.LoadKernelImageResponse
	(*UnloadKernelImageRequest)(nil),  // 3: gkmCsi.UnloadKernelImageRequest
	(*UnloadKernelImageResponse)(nil), // 4: gkmCsi.UnloadKernelImageResponse
}
var file_gkm_csi_proto_depIdxs = []int32{
	0, // 0: gkmCsi.LoadKernelImageRequest.image:type_name -> gkmCsi.ImageLocation
	1, // 1: gkmCsi.GkmCsiService.LoadKernelImage:input_type -> gkmCsi.LoadKernelImageRequest
	3, // 2: gkmCsi.GkmCsiService.UnloadKernelImage:input_type -> gkmCsi.UnloadKernelImageRequest
	2, // 3: gkmCsi.GkmCsiService.LoadKernelImage:output_type -> gkmCsi.LoadKernelImageResponse
	4, // 4: gkmCsi.GkmCsiService.UnloadKernelImage:output_type -> gkmCsi.UnloadKernelImageResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gkm_csi_proto_init() }
func file_gkm_csi_proto_init() {
	if File_gkm_csi_proto != nil {
		return
	}
	file_gkm_csi_proto_msgTypes[0].OneofWrappers = []any{}
	file_gkm_csi_proto_msgTypes[1].OneofWrappers = []any{}
	file_gkm_csi_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gkm_csi_proto_rawDesc), len(file_gkm_csi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gkm_csi_proto_goTypes,
		DependencyIndexes: file_gkm_csi_proto_depIdxs,
		MessageInfos:      file_gkm_csi_proto_msgTypes,
	}.Build()
	File_gkm_csi_proto = out.File
	file_gkm_csi_proto_goTypes = nil
	file_gkm_csi_proto_depIdxs = nil
}
