# permissions for end users to view clustergkmcachenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gpu-kernel-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustergkmcachenode-viewer-role
rules:
- apiGroups:
  - gkm.io
  resources:
  - clustergkmcachenodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gkm.io
  resources:
  - clustergkmcachenodes/status
  verbs:
  - get
