# permissions for end users to view clustergkmcaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: triton-kernel-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustergkmcache-viewer-role
rules:
- apiGroups:
  - gkm.io
  resources:
  - clustergkmcaches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gkm.io
  resources:
  - clustergkmcaches/status
  verbs:
  - get
