# permissions for end users to edit clustergkmcaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: triton-kernel-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustergkmcache-editor-role
rules:
- apiGroups:
  - gkm.io
  resources:
  - clustergkmcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gkm.io
  resources:
  - clustergkmcaches/status
  verbs:
  - get
