# permissions for end users to view gkmcaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: triton-kernel-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: gkmcache-viewer-role
rules:
- apiGroups:
  - gkm.io
  resources:
  - gkmcaches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gkm.io
  resources:
  - gkmcaches/status
  verbs:
  - get
