---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gkm.io
  resources:
  - clustergkmcachenodes
  - clustergkmcaches
  - gkmcachenodes
  - gkmcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gkm.io
  resources:
  - clustergkmcachenodes/finalizers
  - clustergkmcaches/finalizers
  - gkmcachenodes/finalizers
  - gkmcaches/finalizers
  verbs:
  - update
- apiGroups:
  - gkm.io
  resources:
  - clustergkmcachenodes/status
  - clustergkmcaches/status
  - gkmcachenodes/status
  - gkmcaches/status
  verbs:
  - get
  - patch
  - update
