---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tkm.io
  resources:
  - clustertkmcachenodes
  - clustertkmcaches
  - tkmcachenodes
  - tkmcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tkm.io
  resources:
  - clustertkmcachenodes/finalizers
  - clustertkmcaches/finalizers
  - tkmcachenodes/finalizers
  - tkmcaches/finalizers
  verbs:
  - update
- apiGroups:
  - tkm.io
  resources:
  - clustertkmcachenodes/status
  - clustertkmcaches/status
  - tkmcachenodes/status
  - tkmcaches/status
  verbs:
  - get
  - patch
  - update
