apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: gkm-operator-clusterrolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gkm-operator
    app.kubernetes.io/part-of: gkm-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-role
subjects:
- kind: ServiceAccount
  name: operator
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: gkm-operator-clusterrolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gkm-operator
    app.kubernetes.io/part-of: gkm-operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-role
subjects:
- kind: ServiceAccount
  name: agent
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: gkm-operator-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gkm-operator
    app.kubernetes.io/part-of: gkm-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-role
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: gkm-agent-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gkm-operator
    app.kubernetes.io/part-of: gkm-operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gkm-agent-role
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: system
