apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tkm-agent-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: tkm-agent
    namespace: default
roleRef:
  kind: Role
  name: tkm-agent-role
  apiGroup: rbac.authorization.k8s.io
