---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tkm.io
  resources:
  - tritonkernelcacheclusters
  - tritonkernelcachenodestatuses
  - tritonkernelcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tkm.io
  resources:
  - tritonkernelcacheclusters/finalizers
  - tritonkernelcachenodestatuses/finalizers
  - tritonkernelcaches/finalizers
  verbs:
  - update
- apiGroups:
  - tkm.io
  resources:
  - tritonkernelcacheclusters/status
  - tritonkernelcachenodestatuses/status
  - tritonkernelcaches/status
  verbs:
  - get
  - patch
  - update
