apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gkm-agent-role
  namespace: default
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - pods
      - pods/log
      - configmaps
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "gkm.io"
    resources:
      - gkmresources
    verbs:
      - get
      - list
