# permissions for end users to view tritonkernelcachenodestatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: triton-kernel-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: tritonkernelcachenodestatus-viewer-role
rules:
- apiGroups:
  - tkm.io
  resources:
  - tritonkernelcachenodestatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tkm.io
  resources:
  - tritonkernelcachenodestatuses/status
  verbs:
  - get
