# permissions for end users to edit tritonkernelcaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: triton-kernel-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: tritonkernelcache-editor-role
rules:
- apiGroups:
  - tkm.io
  resources:
  - tritonkernelcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tkm.io
  resources:
  - tritonkernelcaches/status
  verbs:
  - get
