---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: gkm-test-cl-rwo-ds-2
  namespace: gkm-test-cl-rwo-1
  labels:
    gkm.io/pvcMutation: "true"
spec:
  selector:
    matchLabels:
      name: gkm-test-cl-rwo-ds-1
  template:
    metadata:
      labels:
        name: gkm-test-cl-rwo-ds-1
        gkm.io/pvc-mutation: "true"
    spec:
      tolerations:
        - key: gpu
          operator: Equal
          effect: NoSchedule
          value: "true"
      nodeSelector:
        gkm-test-node: "true"

      # Init-Container is only needed for KIND clusters.
      initContainers:
        - name: fix-permissions
          image: quay.io/fedora/fedora-minimal
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /cache
              chmod -R 775 /cache
          volumeMounts:
            - name: kernel-volume
              mountPath: /cache

      containers:
        - name: test
          image: quay.io/fedora/fedora-minimal
          imagePullPolicy: IfNotPresent
          command: [sleep, 365d]
          volumeMounts:
            - name: kernel-volume
              mountPath: /cache
      volumes:
        - name: kernel-volume
          persistentVolumeClaim:
            claimName: vector-add-cache-rocm-v2-rwo
