---
apiVersion: v1
kind: Namespace
metadata:
  name: gkm-test-ns-scoped
---
apiVersion: gkm.io/v1alpha1
kind: GKMCache
metadata:
  name: flash-attention-rocm
  namespace: gkm-test-ns-scoped
  annotations:
    gkm.io/resolvedDigest: 424f8764e001f90156067c3035628bcbce666b92db63bcef90fd2ebab9948b43
spec:
  image: quay.io/mtahhan/flash-attention-rocm:latest
---
kind: Pod
apiVersion: v1
metadata:
  name: gkm-test-pod
  namespace: gkm-test-ns-scoped
spec:
  tolerations:
    - key: gpu
      operator: Equal
      effect: NoSchedule
      value: "true"
  nodeSelector:
    gkm-test-node: "true"
  containers:
    - name: alpine
      image: quay.io/fedora/fedora-minimal
      imagePullPolicy: IfNotPresent
      command: [sleep, 365d]
      volumeMounts:
        - name: kernel-volume
          mountPath: /cache
  volumes:
    - name: kernel-volume
      csi:
        driver: csi.gkm.io
        volumeAttributes:
          csi.gkm.io/GKMCache: flash-attention-rocm
          csi.gkm.io/namespace: gkm-test-ns-scoped
