apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  namespace: gkm-system
  labels:
    app: gkm-agent
spec:
  selector:
    matchLabels:
      app: gkm-agent
  template:
    metadata:
      labels:
        app: gkm-agent
    spec:
      serviceAccountName: gkm-agent
      containers:
      - name: gkm-agent
        image: quay.io/gkm/agent:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          privileged: true
          capabilities:
            add: ["CAP_DAC_OVERRIDE", "CAP_FOWNER"]
          seccompProfile:
            type: Unconfined
        env:
          - name: NO_GPU
            valueFrom:
              configMapKeyRef:
                name: gkm-config
                key: gkm.nogpu
          - name: KIND_CLUSTER
            valueFrom:
              configMapKeyRef:
                name: gkm-config
                key: gkm.kindcluster
          - name: GO_LOG
            valueFrom:
              configMapKeyRef:
                name: gkm-config
                key: gkm.agent.log.level
          - name: EXTRACT_IMAGE
            valueFrom:
              configMapKeyRef:
                name: gkm-config
                key: gkm.extract.image
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: /mnt/kernel-caches
            name: kernel-caches
            readOnly: false

      volumes:
        - name: kernel-caches
          hostPath:
            path: /kernel-caches
            type: DirectoryOrCreate