apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  namespace: gkm-system
  labels:
    app: gkm-agent
spec:
  selector:
    matchLabels:
      app: gkm-agent
  template:
    metadata:
      labels:
        app: gkm-agent
    spec:
      containers:
      - name: gkm-agent
        image: quay.io/gkm/agent:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
