---
apiVersion: gkm.io/v1alpha1
kind: GKMCache
metadata:
  name: vector-add-cache-rocm-v3-rwo
  namespace: gkm-test-ns-rwo-1
  labels:
    gkm.io/signature-format: cosign-v3
spec:
  image: quay.io/gkm/cache-examples:vector-add-cache-rocm

  # Toleration is specific to the KIND cluster being deployed.
  podTemplate:
    spec:
      tolerations:
        - key: gpu
          operator: Exists
          effect: NoSchedule
