---
apiVersion: gkm.io/v1alpha1
kind: ClusterGKMCache
metadata:
  name: vector-add-cache-rocm-v2-rox
  labels:
    gkm.io/signature-format: cosign-v2
spec:
  image: quay.io/gkm/cache-examples:vector-add-cache-rocm-v2
  storageClassName: standard
  workloadNamespaces:
    - gkm-test-cl-rox-1
    - gkm-test-cl-rox-2
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
