#docker.io/rocm/vllm:latest
FROM rocm/vllm:latest
ARG ENTRYPOINT_PATH=image/entrypoint-vllm.sh
# Install basic development tools
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install additional dependencies
RUN pip3 install --no-cache-dir \
    transformers \
    accelerate \
    safetensors

# Create non-root user for security
RUN useradd -m -u 2000 vllm
WORKDIR /app
RUN chown vllm:vllm /app

# Create directories for models and benchmarks
RUN mkdir -p /data/benchmarks && \
   chmod 777 /data/benchmarks

# Switch to non-root user
USER vllm

# Make our entrypoint script executable

COPY --chown=vllm:vllm ${ENTRYPOINT_PATH} .
RUN chmod +x entrypoint-vllm.sh

ENTRYPOINT ["./entrypoint-vllm.sh"]

# https://rocm.blogs.amd.com/software-tools-optimization/vllm-container/README.html
